db:
  image: mariadb:10.0
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpass
    - MYSQL_DATABASE=drupal
    - MYSQL_HOME=/etc
  volumes:
    - ./.docker/etc/my.cnf:/etc/my.cnf
  hostname: dbhost
  expose:
    - "3306"
php:
  image: davenuman/bowline-centos
  command: php-fpm
  environment:
    - COMPOSER_HOME=/.composer
  expose:
    - "9000"
  volumes:
    - .:/var/www
  links:
    - db:dbhost
  hostname: php_host
    - .docker/etc/my.cnf:/etc/my.cnf
  hostname: dbhost
  expose:
    - "3306"
  dns:
    - 8.8.8.8
    - 8.8.4.4
web:
  image: davenuman/bowline-web-php:latest
  command: /start.sh
  environment:
    - COMPOSER_HOME=/.composer
  expose:
    - "80"
  links:
    - db:dbhost
    - php:php_host
  volumes_from:
    - php
  hostname: drupal
    - "80" # Exposed public port on deploy
    - "9000"
  volumes:
    - .:/var/www
  links:
    - db:dbhost
  hostname: drupal
  dns:
    - 8.8.8.8
    - 8.8.4.4
web:
  image: davenuman/bowline-centos
  command: httpd -D FOREGROUND -e debug
  expose:
    - "80" # Exposed public port on deploy
  volumes:
    - .:/var/www
