db:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpass
    - MYSQL_DATABASE=drupal
    - MYSQL_HOME=/etc
  volumes:
    - ./.docker/etc/my.cnf:/etc/my.cnf
  hostname: dbhost
  expose:
    - "3306"
  dns:
    - 8.8.8.8
    - 8.8.4.4
web:
  image: davenuman/bowline-web-php:latest
  command: /usr/sbin/apache2 -D FOREGROUND
  environment:
    - COMPOSER_HOME=/.composer
  expose:
    - "80"
  volumes:
    - .:/var/www
  entrypoint: /var/www/lib/bowline/docker-entrypoint.sh
  links:
    - db:dbhost
  hostname: drupal
  dns:
    - 8.8.8.8
    - 8.8.4.4
