<?php

/**
 * @file
 * Contains chhc_message.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function chhc_message_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the chhc_message module.
    case 'help.page.chhc_message':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Messaging for CHHC Foster Hub') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function chhc_message_theme() {
  $theme = [];
  $theme['message_entity'] = [
    'render element' => 'elements',
    'file' => 'message_entity.page.inc',
    'template' => 'message_entity',
  ];
  $theme['message_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'message_entity.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function chhc_message_theme_suggestions_message_entity(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#message_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'message_entity__' . $sanitized_view_mode;
  $suggestions[] = 'message_entity__' . $entity->bundle();
  $suggestions[] = 'message_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'message_entity__' . $entity->id();
  $suggestions[] = 'message_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
