flag.flag.*:
  type: config_entity
  label: 'Flag'
  mapping:
    id:
      type: string
      label: 'Flag identifier'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Name'
    bundles:
      type: sequence
      label: 'The entity bundles this flag applies to'
      sequence:
        - type: string
    entity_type:
      type: string
      label: 'Flaggable entity type'
    enabled:
      type: boolean
      label: 'Whether the flag is enabled'
    global:
      type: boolean
      label: 'Whether the flag is global'
    flag_short:
      type: string
      label: 'Flag link text'
    flag_long:
      type: string
      label: 'Flag link description text'
    flag_message:
      type: string
      label: 'Flag message'
    unflag_short:
      type: string
      label: 'Unflag link text'
    unflag_long:
      type: string
      label: 'Unflag link description text'
    unflag_message:
      type: string
      label: 'Unflag message'
    unflag_denied_text:
      type: string
      label: 'Unflag denied text'
    weight:
      type: integer
      label: 'Weight'
    flag_type:
      type: string
      label: 'ID of the Flag Type plugin'
    link_type:
      type: string
      label: 'ID of the Link Type plugin'
    flagTypeConfig:
      type: flag.flag_type.plugin.[%parent.flag_type]
      label: 'Flag type configuration'
    linkTypeConfig:
      type: flag.link_type.plugin.[%parent.link_type]
      label: 'Link type configuration'

"flag.flag_type.plugin.entity:*":
  type: mapping
  label: 'Flag type for all entity types'
  mapping:
    show_in_links:
      type: sequence
      label: 'Show in links'
      sequence:
        type: string
        label: 'View mode'
    show_as_field:
      type: integer
      label: 'Show as field'
    show_on_form:
      type: integer
      label: 'Show on form'
    show_contextual_link:
      type: integer
      label: 'Show contextual link'

flag.flag_type.plugin.entity:comment:
  type: "flag.flag_type.plugin.entity:*"
  label: 'Flag type for comments'
  mapping:
    access_author:
      type: string
      label: 'Access author'

flag.flag_type.plugin.entity:node:
  type: "flag.flag_type.plugin.entity:*"
  label: 'Flag type for all content entities'
  mapping:
    access_author:
      type: string
      label: 'Access author'
    i18n:
      type: string
      label: 'i18n'

flag.flag_type.plugin.entity:user:
  type: "flag.flag_type.plugin.entity:*"
  label: 'Flag type for  for user entities'
  mapping:
    show_on_profile:
      type: boolean
      label: 'Show on profile'
    access_uid:
      type: string
      label: 'Access uid'

flag.link_type.plugin.*:
  type: mapping
  label: 'Link type configuration'

flag.link_type.plugin.confirm:
  type: mapping
  label: 'Confirm Form link type'
  mapping:
    flag_confirmation:
      type: string
      label: 'Flag confirmation'
    unflag_confirmation:
       type: string
       label: 'Unflag confirmation'

flag.link_type.plugin.field_entry:
  type: mapping
  label: 'Field Entry link type'
  mapping:
    flag_confirmation:
      type: string
      label: 'Flag confirmation'
    edit_flagging:
      type: string
      label: 'Edit flagging'
    unflag_confirmation:
      type: string
      label: 'Unflag confirmation'
